name: Semantic Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  verify:
    name: Validate PR title
    runs-on: ubuntu-slim
    steps:
      # https://github.com/commitizen/conventional-commit-types/blob/master/index.json
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            bug
            fix
            hotfix
            chore
            ci
            feat
            doc
            epic
            perf
            refactor
            release
            revert
            test
            security
            build
